language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'node'
  - '10'
  - '9'
  - '8'
  - '6'
install:
  - npm i
  - npm i -g jest codecov eslint
script:
  - npm run lint
  - snyk auth $SNYK_TOKEN
  - npm test
  - codecov
after_success:
  - snyk monitor
jobs:
  include:
    - stage: release
      node_js: 'node'
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
stages:
  - name: release
    if: branch = master
